language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: true

services:
  - postgresql

addons:
  postgresql: "9.2"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
  - psql -c 'CREATE DATABASE IF NOT EXISTS test;' -U postgres
  - php ./tests/setup.php

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover