language: php

os: linux

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

dist: trusty
sudo: required

services:
  - postgresql

addons:
  postgresql: '9.5'

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - psql -c 'CREATE EXTENSION intarray;' -U postgres -d test
  - psql -c 'CREATE SCHEMA foo;' -U postgres -d test
  - psql -f ./tests/schema.sql -U postgres -d test

script:
  - vendor/bin/php-cs-fixer fix --config=.php_cs --diff --dry-run -v
  - vendor/bin/phpcs -s --config-set ignore_warnings_on_exit 1
  - vendor/bin/phpunit --testsuite Unit --verbose --coverage-clover=coverage.clover
  - vendor/bin/phpunit --testsuite Integration --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false